* financial-markets-class
#+TITLE: 金融市场 on Coursera
https://class.coursera.org/financialmarketszh-002/lecture

http://open.163.com/special/financialmarkets/

** 财务和风险管理的基本原则
没有最佳资产组合(portfolio): 有着高回报(expected)的投资组合一定同样有着高风险(variance)的。但是我们却可以通过多样化投资来分散风险和提高回报率。下图是一张投资组合曲线，横轴是variance, 纵轴则是回报率。可以看到如果投资石油的话，相比不投资石油，我们可以找到一个更好的投资组合点。绘制这个图最复杂之处是，需要我们知道每种投资方式的期望方差以及两种投资之间的协方差。

file:./images/fm-class-about-portfolio.png

可是如果我们考虑有风险为0的稳定投资选择的话，那么其实还是有"最优投资组合"的。这个"最优投资组合"就是下图中的切线，称为"切线资产组合"(tangency portfolio). 就此出发还有一个理论就是共同基金定理(mutual fund theorem), 它们只投资这个切线资产组合。但是这个理论隐含的假设是，市场资产组合必须和切线资产组合一样，但是这点在现实中不一定成立。比如切线资产组合要求石油和债券比例是10:1, 但是市场中十余和债券比例只有2:1.

我们从上图中还可以看到另外一个问题，就是通过杠杆率我们其实可以将收益率抬得非常高，但是方差也变得更大。所以如果有人宣称我们有很高的投资回报率时，我们要注意到它是否使用了高杠杆率来提高收益率。一个比较衡量指标就是SharpRatio(夏普系数) = (R(portfolio) - Rf) / Var(portfolio).(Rf指无风险收益率) 使用这个指标可以排除杠杆率的影响。

那我们如何管理风险呢？一个办法就是保险(insurance). 保险本质上是风险公担(risk pooling). 保险这个概念不复杂，但是却有很多细节问题，其中包括moral hazard(道德风险): 比如购买火灾保险但是却自己烧掉房子，购买人寿保险但是自杀等等。我们需要通过一系列手段来解决比如合同，限制保险金额，逆向选择(selection bias, 保险公司来选择投保人群)，明确损失含义等等。作者提到了08年美国大萧条时候只对AIG进行救助(承诺$182 billion)，是因为担心出现系统性风险(systemetic risk), 一旦AIG瘫痪那么几乎所有的经济活动都要停止(or 金融瘫痪)。这段历史在 [[file:note/inside-job.org][监守自盗(Inside Job)]] 里面也有说到。

** 有效市场与行为金融
有效市场假说认为股票价格可以充分反应市场信息，因为人们一旦获得信息的话那么立刻会在股票价格上反应出来。人们获得信息速度是不同的，不过当信息完全传播之后股票价格会回到它真实价值。因为市场信息本身就是完全随机的，所以按照有效市场假说的话，股票价格应该是符合随机漫步模型(random walk, X(t) = X(t-1) + p, 其中p是一个mean=0符合高斯分布的随机扰动)。关于AR-1部分我没有想到这个和有效市场有什么具体关联，AR-1给出的公式是X(t) = base + k * (X(t-1) - base) + p. 其中base为价格回归值，k为回归系数，p则为扰动。我猜想Shiller要说的意思应该是，股票价格并不是一个随机漫步模型，更应该是一个AR-1模型但是k非常接近1.

但是有效市场并不能够解释所有金融现象，人类心理因素和自身限制还会影响到投资行为和市场，这就是行为金融的假设和是研究问题。作者在视频中给出了影响金融的几个行或行为理论，包括前景理论(prospect theorey，人们如何看待未来事物)：包含价值函数（人们是如何看待财富/金钱和效用/value之间的关系，人们对于细微的损失在意程度远超过细微的盈利）和权重函数（人们如何来衡量和看待事物发生的概率，人们不会连续性地思考概率）；后悔理论(regret theorey，人们为了避免过去犯的错误而做出的糟糕决定)；赌博行为(gambling, 股票在某种程度上也是赌博行为)；过度自信(over-confidence. 这个例子非常有意思，我们通常认为CEO都是天才或者是如果成功管理过某个公司的CEO是天才，所以如果公司不太景气的话那么最好从其他公司请个CEO. 但是这些CEO有可能只是比较走运之前做成功了，或者是他之前比较了解公司。如果来到新公司的话，因为不熟悉情况，可能会进行大规模裁员将公司重新洗牌，就此毁了原有一切)；认知失调(cognitive dissonance, 承认自己深信不疑的东西是错误的，这点是非常痛苦的，于是人们总是试图寻找新的证据来支撑。但是因为他的信念中包含了对自我的肯定，于是就有了偏见)；社会蔓延效应(social contagion, 社会感染. 个人想法会受到社会中其他群体以及这个时代主流想法的影响)

** 债务与股票
- 公司 # corporation, corpus, 法人(legal person), 自然人(nature person)
- 股权 # equity. 每个股东是平等的，每人只能投一票，但是也有无投票权的股权
- 董事会 # board of directors. 在股东大会上股东们选举出
- CEO # 同样在股东大会上选举出，并且作为公司雇员向董事会汇报
- 市值 # marker cap/capitalization = value per share * # of shares. 股价 * 股份数
- 分红 # dividend. 如果董事会决定的话，红利(利润)会发放给股东，但是它们不一定要这么做。但是最终还是会发放红利的，不然就是非营利性公司。
  - 人们买股票的原因是因为它会涨，但是背后原因是人们认为他们可以通过股票获取更多的红利才购买的，至少理论上是这样的。
  - 一旦发放了红利(利润), 很自然公司的市值就减少了，所以股价就会发生下跌。当天的股价会标注x(x dividend price), 说明股价下降是因为分红造成的。
  - 虽然是董事会决定是否应该发放红利，可是如果董事会不发放的话，那么股东可以重新选出新的董事会。
- 摊薄效应 # dilution. 公司决定发行更多的股票（得到更多的资金）造成的效应。于此相对应的行为是回购股票(repurchase)
- 优先股 # preferred stock. 相比于普通股 1. 没有投票权 2. 红利是固定，但是如果有红利的话优先满足。优先股有点类似债券

-----

http://open.163.com/special/cuvocw/jinrongshihexin.html Lecture5

证券交易所
|          | 场内交易/证券交易所                                   | 场外交易       |
|----------+-------------------------------------------------------+----------------|
| 场所     | 固定，有形市场                                        | 分散，无形市场 |
| 制度     | 经纪人制度                              | 做市商制       |
| 交易证券 | 上市证券                                              | 多为非上市证券 |
| 交易价格 | 竞价 | 协商           |
| 监管     | 严格                                                  | 宽松           |
- 证券交易所分为公法人性质（非营利性）和公司性质（营利性)。
- 场内交易我们委托证券公司经纪人(broker)来做交易，不可避免地证券公司需要收取高额的佣金(commission)和管理费用。
- 以上交所为例的话，每天9：30开盘但是9：00就可以开始报价，然后经过系统撮合完成交易。
- 经纪人完成的是代理买卖，经纪人也可以进行自营买卖(dealer)，但是自营买卖对于经纪人道德要求比较高，因为同时做自营可能会损害客户利益。
- 一级市场(新证券发行市场，交易额可以计入GDP)和二级市场(证券交易市场，除了印花和交易税之外的交易额不可以计入GDP).

股票
- 各种分类方法
  - 普通股和优先股。优先股分为累积性优先股(没有发放红利的一年会累积下来下次补发)和非累积性优先股(不会补发)
  - 记名股票(不可以自由转让，转让需要董事会批准)和不记名股票.
  - 有面额股票(国内股票大部分为1元/股)和无面额股票.
  - 可上市股票和非上市股票(没有在交易所挂牌交易).
- 股票价格
  - 票面价格(1元), 账面价格(买入价格), 市场价格/交易价格
  - 发行价格：平行发行(发行价=票面价), 折价发行，溢价发行
- 价格指数
  - 综合指数和成分指数
  - 简单平均和加权平均
