* financial-markets-class
#+TITLE: 金融市场 on Coursera
https://class.coursera.org/financialmarketszh-002/lecture

** 财务和风险管理的基本原则
没有最佳资产组合(portfolio): 有着高回报(expected)的投资组合一定同样有着高风险(variance)的。但是我们却可以通过多样化投资来分散风险和提高回报率。下图是一张投资组合曲线，横轴是variance, 纵轴则是回报率。可以看到如果投资石油的话，相比不投资石油，我们可以找到一个更好的投资组合点。绘制这个图最复杂之处是，需要我们知道每种投资方式的期望方差以及两种投资之间的协方差。

file:./images/fm-class-about-portfolio.png

可是如果我们考虑有风险为0的稳定投资选择的话，那么其实还是有"最优投资组合"的。这个"最优投资组合"就是下图中的切线，称为"切线资产组合"(tangency portfolio). 就此出发还有一个理论就是共同基金定理(mutual fund theorem), 它们只投资这个切线资产组合。但是这个理论隐含的假设是，市场资产组合必须和切线资产组合一样，但是这点在现实中不一定成立。比如切线资产组合要求石油和债券比例是10:1, 但是市场中十余和债券比例只有2:1.

我们从上图中还可以看到另外一个问题，就是通过杠杆率我们其实可以将收益率抬得非常高，但是方差也变得更大。所以如果有人宣称我们有很高的投资回报率时，我们要注意到它是否使用了高杠杆率来提高收益率。一个比较衡量指标就是SharpRatio(夏普系数) = (R(portfolio) - Rf) / Var(portfolio).(Rf指无风险收益率) 使用这个指标可以排除杠杆率的影响。

那我们如何管理风险呢？一个办法就是保险(insurance). 保险本质上是风险公担(risk pooling). 保险这个概念不复杂，但是却有很多细节问题，其中包括moral hazard(道德风险): 比如购买火灾保险但是却自己烧掉房子，购买人寿保险但是自杀等等。我们需要通过一系列手段来解决比如合同，限制保险金额，逆向选择(selection bias, 保险公司来选择投保人群)，明确损失含义等等。作者提到了08年美国大萧条时候只对AIG进行救助(承诺$182 billion)，是因为担心出现系统性风险(systemetic risk), 一旦AIG瘫痪那么几乎所有的经济活动都要停止(or 金融瘫痪)。这段历史在 [[file:note/inside-job.org][监守自盗(Inside Job)]] 里面也有说到。
