#!/bin/bash
# publish org files.

# find emacs.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" = "DarwinX" ]
then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

# generate html files.
$emacs --batch --script publish.el
if [ $? != 0 ]
then
    echo "publish failed!"
    exit 1
fi

# post-process html files.
./pp-html

# rsync images and css files.
rsync -avrz images/ ../../dirtysalt.github.io/images/
rsync -avrz css/ ../../dirtysalt.github.io/css/
