* the-anatomy-of-the-perfect-technical-interview-from-a-former-amazon-vp
#+TITLE: The Anatomy of the Perfect Technical Interview from a Former Amazon VP

http://firstround.com/review/The-anatomy-of-the-perfect-technical-interview-from-a-former-Amazon-VP/

作者[[https://www.crunchbase.com/person/neil-roseman][Neil Roseman]]是Amazon和Zynga的前技术VP.

开始面试之前：
- You should come out of every interview with a clear sense of whether the person could improve the probability of your company’s success. # 能够清楚地辨认某人是否可以增加公司成功几率。
- Great interviewing is work. It takes time to prepare, conduct the interview and then de-brief in an effective way. If you don’t want to do the work, don’t interview. # 面试也是工作，因此要为此腾出时间，做好功课。
- Once you form an initial impression of someone - which usually happens within the first 60 seconds - you should spend the rest the interview trying to invalidate that impression. # 通常在60s内你就会对面试者有初始印象，接下来的时间你要检验你这些感觉是否正确
- You should always take copious notes during interviews so you can make a cogent argument for or against a candidate. # 做好面试记录以便可以给出让人信服的赞成或反对理由
- In most cases, the “best and the brightest” already have jobs, so you’re really just on the lookout for the best available. Plus there’s no way to prove that your hiring process resulted in the right people because you can’t A/B test hiring decisions. # 招聘没有办法做AB测试，所以没有办法确定某种流程就一定能找到正确的人。
- Always strive to hire superstars but realize that not all hires need to “walk on water.” This person should be better along some dimensions than a majority of the current staff and have the potential to have a long-term impact. # 人不能十全十美，但是它们必须在某个方面比其他人做的更好，并且能够发挥长期作用。
- You want to hire people who are smart, that get stuff done and have the functional set of skills you need for the role. # 聪明并且能够搞定事情。

阅读简历和设计问题：
- the least experience in is how to read a resume, identify the areas worth probing, and determining how to probe into them. # 如何阅读简历，找出那些方面值得去提问，并且选择正确方式去提问
- This is how he develops most of his questions. “You want to find out what somebody really did, as opposed to just being an observer or a participant,” Roseman says. “Even at the greatest companies, there’s a gap between those who get the most stuff done and those who don’t get much done. You need to try and figure that out during an interview.” # 就Roseman来说，他会就面试者工作经历，看他是否真的参与其中，还是旁观。
- In many cases, this can be a litmus test for how clearly they think about themselves and their role as well. “They might think it sounds good to say 'I improved system availability by 50%', but if we’re hiring someone for a system engineering role, I need to know they actually did that. In most cases with high level statements like this — which appear on resumes all the time — the person actually hasn’t done it or was just a participant, and understands very little. They won’t have a very clear answer.” The good candidates will be able to explain and backup their claims no matter how far you drill down.
- To put this another way, great interview questions focus on specific examples of the candidate’s unique contributions, actions, decisions and impact. Ideally, you want to:
  - Probe: give me an example # 你做了什么项目？
  - Dig: who, what, where, when, why and how on every accomplishment or project # 在项目中做了哪些事情？
  - Differentiate: we vs. I, good vs. great, exposure vs. expertise, participant vs. owner/leader, 20 yard line vs. 80 yard line # 个人在项目中角色以及表现
- Roseman goes on to share, “I look for past projects and accomplishments that seem to have enough weight and depth that I can apply STAR questions — STAR stands for situation, task, actions and results.” Roseman subscribes heavily to an approach called Behavioral Interviewing, in which STAR questions are a staple. They include: # 针对那些有分量和深度的项目进行STAR
  - What was the background of what you were working on?
  - What tasks were you given?
  - What actions did you take?
  - What results did you measure?

技术问题和面试流程

