* 1984
#+TITLE: 1984

在温斯顿的身后，电幕上的声音仍在喋喋不休地报告生铁产量和第九个三年计划的超额完成情况。电幕能够同时接收和放送。温斯顿发出的任何声音，只要比极低声的细语大一点，它就可以接收到；此外，只要他留在那块金属板的视野之内，除了能听到他的声音之外，也能看到他的行动。当然，没有办法知道，在某一特定的时间里，你的一言一行是否都有人在监视着。思想警察究竟多么经常，或者根据什么安排在接收某个人的线路，那你就只能猜测了。甚至可以想象，他们对每个人都是从头到尾一直在监视着的。反正不论什么时候，只要他们高兴，他们都可以接上你的线路。你只能在这样的假定下生活——从已经成为本能的习惯出发，你早已这样生活了：你发出的每一个声音，都是有人听到的，你作的每一个动作，除非在黑暗中，都是有人仔细观察的。

温斯顿继续背对着电幕。这样比较安全些；不过他也很明白，甚至背部有时也能暴露问题的。一公里以外，他工作的单位真理部高耸在阴沉的市景之上，建筑高大，一片白色。这，他带着有些模糊的厌恶情绪想——这就是伦敦，一号空降场的主要城市，一号空降场是大洋国人口位居第三的省份。他竭力想挤出一些童年时代的记忆来，能够告诉他伦敦是不是一直都是这样的。是不是一直有这些景象：破败的十九世纪房子，墙头用木材撑着，窗户钉上了硬纸板，屋顶上盖着波纹铁皮，倒塌的花园围墙东倒西歪；还有那尘土飞扬、破砖残瓦上野草丛生的空袭地点；还有那炸弹清出了一大块空地，上面忽然出现了许多象鸡笼似的肮脏木房子的地方。可是没有用，他记不起来了；除了一系列没有背景、模糊难辨的、灯光灿烂的画面以外，他的童年已不留下什么记忆了。

从温斯顿站着的地方，正好可以看到党的三句口号，这是用很漂亮的字体写在白色的墙面上的： 战争即和平 自由即奴役 无知即力量。

它们是整个政府机构四部的所在地：真理部负责新闻、娱乐、教育、艺术；和平部负责战争；友爱部维持法律和秩序；富裕部负责经济事务。用新话来说，它们分别称为真部、和部、爱部、富部。

照理党员是不许到普通店铺里去的(去了就是“在自由市场上做买卖”)，不过这条规矩并不严格执行，因为有许多东西，例如鞋带、刀片，用任何别的办法是无法弄到的，他回头很快地看了一眼街道两头，就溜进了小铺子，花二元五角钱把本子买了下来。当时他并没有想到买来干什么用。他把它放在皮包里，不安地回了家。即使里面没有写什么东西，有这样一个本子也是容易引起怀疑的。

他呆呆地坐在那里，看着本子。电幕上现在播放刺耳的军乐了。奇怪的是，他似乎不仅丧失了表达自己的能力，而且甚至忘掉了他原来要想说什么话了。过去几个星期以来，他一直在准备应付这一时刻，他从来没有想到过，除了勇气以外还需要什么。实际写作会是很容易的。他要做的只是把多年来头脑里一直在想的、无休止的、无穷尽的独白付诸笔墨就行了。但是在目前，甚至独白也枯竭了。

果尔德施坦因是个叛徒、变节分子，他一度(那是很久以前了，到底多久，没有人记得清楚)是党的领导人物之一，几乎与老大哥本人平起平坐，后来从事反革命活动，被判死刑，却神秘地逃走了，不知下落。两分钟仇恨节目每天不同，但无不以果尔德施坦因为其重要人物。他是头号叛徒，最早污损党的纯洁性的人。后来的一切反党罪行、一切叛国行为、破坏颠覆、异端邪说、离经叛道都是直接起源于他的教唆。反正不知在什么地方，他还活着，策划着阴谋诡计；也许是在海外某个地方，得到外国后台老板的庇护；也许甚至在大洋国国内某个隐蔽的地方藏匿着——有时就有这样的谣传。

两分钟仇恨所以可怕，不是你必须参加表演，而是要避不参加是不可能的。不出三十秒钟，一切矜持都没有必要了。一种夹杂着恐惧和报复情绪的快意，一种要杀人、虐待、用大铁锤痛打别人脸孔的欲望，似乎象一股电流一般穿过了这一群人，甚至使你违反本意地变成一个恶声叫喊的疯子。然而，你所感到的那种狂热情绪是一种抽象的、无目的的感情，好象喷灯的火焰一般，可以从一个对象转到另一个对象。因此，有一阵子，温斯顿的仇恨并不是针对果尔德施坦因的，而是反过来转向了老大哥、党、思想警察；在这样的时候，他打从心跟里同情电幕上那个孤独的、受到嘲弄的异端分子，谎话世界中真理和理智的唯一卫护者。可是一会儿他又同周围的人站在一起，觉得攻击果尔德施坦因的一切的话都是正确的。在这样的时刻，他心中对老大哥的憎恨变成了崇拜，老大哥的形象越来越高大，似乎是一个所向无故、毫无畏惧的保护者，象块巨石一般耸立于从亚洲蜂拥而来的乌合之众之前，而果尔德施坦因尽管孤立无援，尽管对于是否有他这个人的存在也有怀疑，却似乎是一个阴险狡诈的妖物，光凭他的谈话声音也能够把文明的结构破坏无遗。

总是在夜里——逮捕总是在夜里进行的。突然在睡梦中惊醒，一只粗手捏着你的肩膀，灯光直射你的眼睛，床边围着一圈凶狠的脸孔。在绝大多数情况下不举行审讯，不报道逮捕消息，人就是这么销声匿迹了，而且总是在夜里。你的名字从登记册上除掉了，你做过的一切事情的记录都除掉了，你的一度存在也给否定了，接着被遗忘了。你被取消，消灭了：通常用的字眼是化为乌有(vaporized)。

他心中想，有这样的孩子，那个可怜的女人的日子一定过得够呛。再过一、两年，他们就要日日夜夜地监视着她，看她有没有思想不纯的迹象。如今时世，几乎所有的孩子都够呛。最糟糕的是，通过象少年侦察队这样的组织，把他们有计划地变成了无法驾驭的小野人，但是这却不会在他们中间产生任何反对党的控制的倾向。相反，他们崇拜党和党的一切。唱歌、游行、旗帜、远足、木枪操练、高呼口号、崇拜老大哥——所有这一切对他们来说都是非常好玩的事。

他们的全部凶残本性都发泄出来，用在国家公敌，用在外国人、叛徒、破坏分子、思想犯身上了。三十岁以上的人惧怕自己的孩子几乎是很普遍的事。这也不无理由，因为每星期《泰晤士报》总有一条消息报道有个偷听父母讲话的小密探——一般都称为“小英雄”——偷听到父母的一些见不得人的话，向思想警察作了揭发。
