* 1984
#+TITLE: 1984

在温斯顿的身后，电幕上的声音仍在喋喋不休地报告生铁产量和第九个三年计划的超额完成情况。电幕能够同时接收和放送。温斯顿发出的任何声音，只要比极低声的细语大一点，它就可以接收到；此外，只要他留在那块金属板的视野之内，除了能听到他的声音之外，也能看到他的行动。当然，没有办法知道，在某一特定的时间里，你的一言一行是否都有人在监视着。思想警察究竟多么经常，或者根据什么安排在接收某个人的线路，那你就只能猜测了。甚至可以想象，他们对每个人都是从头到尾一直在监视着的。反正不论什么时候，只要他们高兴，他们都可以接上你的线路。你只能在这样的假定下生活——从已经成为本能的习惯出发，你早已这样生活了：你发出的每一个声音，都是有人听到的，你作的每一个动作，除非在黑暗中，都是有人仔细观察的。

温斯顿继续背对着电幕。这样比较安全些；不过他也很明白，甚至背部有时也能暴露问题的。一公里以外，他工作的单位真理部高耸在阴沉的市景之上，建筑高大，一片白色。这，他带着有些模糊的厌恶情绪想——这就是伦敦，一号空降场的主要城市，一号空降场是大洋国人口位居第三的省份。他竭力想挤出一些童年时代的记忆来，能够告诉他伦敦是不是一直都是这样的。是不是一直有这些景象：破败的十九世纪房子，墙头用木材撑着，窗户钉上了硬纸板，屋顶上盖着波纹铁皮，倒塌的花园围墙东倒西歪；还有那尘土飞扬、破砖残瓦上野草丛生的空袭地点；还有那炸弹清出了一大块空地，上面忽然出现了许多象鸡笼似的肮脏木房子的地方。可是没有用，他记不起来了；除了一系列没有背景、模糊难辨的、灯光灿烂的画面以外，他的童年已不留下什么记忆了。

从温斯顿站着的地方，正好可以看到党的三句口号，这是用很漂亮的字体写在白色的墙面上的： 战争即和平 自由即奴役 无知即力量。

它们是整个政府机构四部的所在地：真理部负责新闻、娱乐、教育、艺术；和平部负责战争；友爱部维持法律和秩序；富裕部负责经济事务。用新话来说，它们分别称为真部、和部、爱部、富部。

照理党员是不许到普通店铺里去的(去了就是“在自由市场上做买卖”)，不过这条规矩并不严格执行，因为有许多东西，例如鞋带、刀片，用任何别的办法是无法弄到的，他回头很快地看了一眼街道两头，就溜进了小铺子，花二元五角钱把本子买了下来。当时他并没有想到买来干什么用。他把它放在皮包里，不安地回了家。即使里面没有写什么东西，有这样一个本子也是容易引起怀疑的。

他呆呆地坐在那里，看着本子。电幕上现在播放刺耳的军乐了。奇怪的是，他似乎不仅丧失了表达自己的能力，而且甚至忘掉了他原来要想说什么话了。过去几个星期以来，他一直在准备应付这一时刻，他从来没有想到过，除了勇气以外还需要什么。实际写作会是很容易的。他要做的只是把多年来头脑里一直在想的、无休止的、无穷尽的独白付诸笔墨就行了。但是在目前，甚至独白也枯竭了。

果尔德施坦因是个叛徒、变节分子，他一度(那是很久以前了，到底多久，没有人记得清楚)是党的领导人物之一，几乎与老大哥本人平起平坐，后来从事反革命活动，被判死刑，却神秘地逃走了，不知下落。两分钟仇恨节目每天不同，但无不以果尔德施坦因为其重要人物。他是头号叛徒，最早污损党的纯洁性的人。后来的一切反党罪行、一切叛国行为、破坏颠覆、异端邪说、离经叛道都是直接起源于他的教唆。反正不知在什么地方，他还活着，策划着阴谋诡计；也许是在海外某个地方，得到外国后台老板的庇护；也许甚至在大洋国国内某个隐蔽的地方藏匿着——有时就有这样的谣传。

两分钟仇恨所以可怕，不是你必须参加表演，而是要避不参加是不可能的。不出三十秒钟，一切矜持都没有必要了。一种夹杂着恐惧和报复情绪的快意，一种要杀人、虐待、用大铁锤痛打别人脸孔的欲望，似乎象一股电流一般穿过了这一群人，甚至使你违反本意地变成一个恶声叫喊的疯子。然而，你所感到的那种狂热情绪是一种抽象的、无目的的感情，好象喷灯的火焰一般，可以从一个对象转到另一个对象。因此，有一阵子，温斯顿的仇恨并不是针对果尔德施坦因的，而是反过来转向了老大哥、党、思想警察；在这样的时候，他打从心跟里同情电幕上那个孤独的、受到嘲弄的异端分子，谎话世界中真理和理智的唯一卫护者。可是一会儿他又同周围的人站在一起，觉得攻击果尔德施坦因的一切的话都是正确的。在这样的时刻，他心中对老大哥的憎恨变成了崇拜，老大哥的形象越来越高大，似乎是一个所向无故、毫无畏惧的保护者，象块巨石一般耸立于从亚洲蜂拥而来的乌合之众之前，而果尔德施坦因尽管孤立无援，尽管对于是否有他这个人的存在也有怀疑，却似乎是一个阴险狡诈的妖物，光凭他的谈话声音也能够把文明的结构破坏无遗。

总是在夜里——逮捕总是在夜里进行的。突然在睡梦中惊醒，一只粗手捏着你的肩膀，灯光直射你的眼睛，床边围着一圈凶狠的脸孔。在绝大多数情况下不举行审讯，不报道逮捕消息，人就是这么销声匿迹了，而且总是在夜里。你的名字从登记册上除掉了，你做过的一切事情的记录都除掉了，你的一度存在也给否定了，接着被遗忘了。你被取消，消灭了：通常用的字眼是化为乌有(vaporized)。

他心中想，有这样的孩子，那个可怜的女人的日子一定过得够呛。再过一、两年，他们就要日日夜夜地监视着她，看她有没有思想不纯的迹象。如今时世，几乎所有的孩子都够呛。最糟糕的是，通过象少年侦察队这样的组织，把他们有计划地变成了无法驾驭的小野人，但是这却不会在他们中间产生任何反对党的控制的倾向。相反，他们崇拜党和党的一切。唱歌、游行、旗帜、远足、木枪操练、高呼口号、崇拜老大哥——所有这一切对他们来说都是非常好玩的事。

他们的全部凶残本性都发泄出来，用在国家公敌，用在外国人、叛徒、破坏分子、思想犯身上了。三十岁以上的人惧怕自己的孩子几乎是很普遍的事。这也不无理由，因为每星期《泰晤士报》总有一条消息报道有个偷听父母讲话的小密探——一般都称为“小英雄”——偷听到父母的一些见不得人的话，向思想警察作了揭发。

但是这种知识存在于什么地方呢？只存在于他自己的意识之中，而他的意识反正很快就要被消灭的。如果别人都相信党说的谎话——如果所有记录都这么说——那么这个谎言就载入历史而成为真理。党的一句口号说，“谁控制过去就控制未来；谁控制现在就控制过去。”虽然从其性质来说，过去是可以改变的，但是却从来没有改变过。凡是现在是正确的东西，永远也是正确的。这很简单。所需要的只是一而再再而三，无休无止地克服你自己的记忆。他们把这叫做“现实控制”；用新话来说是“双重思想”。

不论哪一天的《泰晤士报》，凡是需要更正的材料收齐核对以后，那一天的报纸就要重印，原来的报纸就要销毁，把改正后的报纸存档。这种不断修改的工作不仅适用于报纸，也适用于书籍、期刊、小册子、招贴画、传单、电影、录音带、漫画、照片——凡是可能具有政治意义或思想意义的一切文献书籍都统统适用。每天，每时，每刻，都把过去作了修改，使之符合当前情况。这样，党的每一个预言都有文献证明是正确的。凡是与当前需要不符的任何新闻或任何意见，都不许保留在纪录上。全部历史都象一张不断刮干净重写的羊皮纸。这一工作完成以后，无论如何都无法证明曾经发生过伪造历史的事。纪录司里最大的一个处——比温斯顿工作的那个处要大得多——里工作人员的工作，就是把凡是内容过时而需销毁的一切书籍、报纸和其他文件统统收回来。由于政治组合的变化，或者老大哥预言的错误，有些天的《泰晤士报》可能已经改写过了十几次，而犹以原来日期存档，也不留原来报纸，也不留其他版本，可证明它不对。书籍也一而再、再而三地收回来重写，重新发行时也从来不承认作过什么修改。甚至温斯顿收到的书面指示——他处理之后无不立即销毁的——也从来没有明言过或暗示过要他干伪造的勾当，说的总是为了保持正确无误，必须纠正一些疏忽、错误、排印错误和引用错误。

更可能的是，没有人知道究竟生产了多少双，更没有人关心这件事。你所知道的只是，每个季度在纸面都生产了天文数字的鞋子，但是大洋国里却有近一半的人口打赤脚。每种事实的纪录都是这样，不论大小。一切都消隐在一个影子世界里，最后甚至连今年是哪一年都弄不清了。

真理部不仅要满足党的五花八门的需要，而且也要全部另搞一套低级的东西供无产阶级享用，因此另设一系列不同的部门，负责无产阶级文学、戏剧、音乐我一般的娱乐，出版除了体育运动、凶杀犯罪、天文星象以外没有任何其他内容的无聊报纸，廉价的刺激小说，色情电影，靡靡之音，后者这种歌曲完全是用一种叫做谱曲器的特殊机器用机械的方法谱写出来的。甚至有一科——新话叫色科——专门负责生产最低级的色情文学，密封发出，除了有关工作人员外，任何党员都不得偷看。

他现在打开他原先放在一边的那份指示。上面是： 泰晤士3.12.83报道老大命令双加不好提到非人全部重写存档前上交。 用老话(或者标准英语)这可以译为： 1983年12月3日《泰晤士报》报道老大哥命令的消息极为不妥，因为它提到不存在的人。全部重写，在存档前将你草稿送上级审查。

这是意料中事，因为对政治犯一般并不经常进行公开审判或者甚至公开谴责的。对成千上万的人进行大清洗，公开审判叛国犯和思想犯，让他们摇尾乞怜地认罪然后加以处决，这样专门摆布出来给大家看，是过一两年才有一遭的事。比较经常的是，干脆让招党不满的入就此失踪，不知下落。谁也一点不知道，他们究竟遭到什么下场。有些人可能根本没有死。温斯顿相识的人中，先后失踪的就有大约三十来个人，还不算他们的父母。

“消灭词汇是件很有意思的事情。当然，最大的浪费在于动词和形容词，但是也有好几百个名词也可以不要。不仅是同义词，也包括反义词。说真的，如果一个词不过是另一个词的反面，那有什么理由存在呢？以‘好’为例。如果你有一个‘好’宇，为什么还需要‘坏’字？‘不好’就行了——而且还更好，因为这正好是‘好’的反面，而另外一字却不是。再比如，如果你要一个比‘好’更强一些的词儿，为什么要一连串象‘精采’、‘出色’等等含混不清、毫无用处的词儿呢？

“你难道不明白，新话的全部目的是要缩小思想的范围？ 最后我们要使得大家在实际上不可能犯任何思想罪，因为将来没有词汇可以表达。凡是有必要使用的概念，都只有一个词来表达，意义受到严格限制，一切附带含意都被消除忘掉。在十一版中，我们距离这一目标已经不远了。但这一过程在你我死后还需要长期继续下去。词汇逐年减少，意识的范围也就越来越小。当然，即使在现在，也没有理由或借口可以犯思想罪。这仅仅是个自觉问题，现实控制问题。但最终，甚至这样的需要也没有了。语言完善之时，即革命完成之日。新话即英社，英社即新话，”

“新话中有一个词儿，”赛麦说，“我不知道你是不是知道，叫鸭话(duckspeak)，就是象鸭子那样呱呱叫。这种词儿很有意思，它有两个相反的含意。用在对方，这是骂人的；用在你同意的人身上，这是称赞。”

电幕上继续不断地播送神话般的数字。同去年相比，食物、衣服、房屋、家俱、铁锅、燃料、轮船、直升飞机、书籍、婴孩的产量都增加了——除了疾病、犯罪、发疯以外，什么都增加了。逐年逐月，每时每刻，不论什么人，什么东西都在迅速前进。象赛麦原来在做的那样，温斯顿拿起汤匙，蘸着桌子上的那一摊灰色的粘糊糊，画了一道长线，构成一个图案。他不快地沉思着物质生活的各个方面。一直是这样的吗？他的饭一直是这个味道？他环顾食堂四周，一间天花板很低、挤得满满的屋子，由于数不清的人体接触，墙头发黑；破旧的铁桌铁椅挨得很近，你坐下来就碰到别人的手肘；汤匙弯曲，铁盘凹凸，白缸子都很祖糙；所有东西的表面都油腻腻的，每一条缝道里都积满尘垢；到处都弥漫着一股劣质杜松子酒、劣质咖啡、涮锅水似的炖菜和脏衣服混合起来的气味。在你的肚子里，在你的肌肤里，总发出一种无声的抗议，一种你被骗掉了有权利享受的东西的感觉。不错，他从来记不起还有过什么东西与现在大不相同。凡是他能够确切记得起来的，不论什么时候，总是没有够吃的东西，袜子和内衣裤总是有破洞的，家俱总是破旧不堪的，房间里的暖气总是烧得不暖的，地铁总是拥挤的，房子总是东倒西歪的，面包总是深色的，茶总是喝不到，咖啡总是有股脏水味，香烟总是不够抽——除了人造杜松子酒以外，没有东西是又便宜又多的。虽然这样的情况必然随着你的体格衰老而越来越恶劣，但是，如果你因为生活艰苦、污秽肮脏、物质匮乏而感到不快，为没完没了的寒冬、破烂的袜子、停开的电梯、寒冷的自来水、粗糙的肥皂、自己会掉烟丝的香烟、有股奇怪的难吃味道的食物而感到不快，这岂不是说明，这样的情况不是(not)事物的天然规律？除非你有一种古老的回忆，记得以前事情不是这样的，否则的话，你为什么要觉得这是不可忍受的呢？
