* why-cn-people-anxious
#+TITLE: 中国人的焦虑从哪里来

在过去的人类社会中，有权有势的人可以凭权势剥夺别人所创造的财富，所以人们追求权势而不追求财富。可是权势具有排他性，皇帝只有一个，我当了你就不能当，所以纷争不断。而财富没有排他性，你能发财，我也能发财，所以大家都去争创财富。当特权受限制时，人们开始努力创造财富，而不是追求权势，这个社会的财富创造有了突飞猛进的发展。其结果是社会中最穷的人，境况也能有所改善。

地位的平等比财富的平等更重要，还有一层原因，就是金钱和权势的勾结。财富不平等的原因之一是依靠权势获得财富，而且这部分财富的不平等不利于社会财富的增加，它是掠夺性的。比如以权谋私，贪污腐化，它们造成财富的差别，但是没有财富的创造。在市场规则之下，财富的差别是和财富的创造相联系的。

现在看来，在发达国家里收入差距依然存在，但是地位的不平等基本已经消除。可见收入的不平等不容易纠正，而地位的不平等是可以纠正的。我们应该对收入差距保持宽容，对地位的不平等要努力消除。可惜我们似乎正在走一条相反的路。当前大家关注我国的贫富分化，成为全社会的焦点。但是大家对社会地位的不平等熟视无睹，任其存在，甚至还在发展。这种轻重失据的社会关注可能会严重误导我国的进一步改革开放。

分析到这儿，我们明白了，经济上的不平等是为了鼓励财富的生产，没有这点不平等，大家都想搭便车，社会将要越来越穷。要将财富分配给创造它的人，这样造成的不平等虽然不好，但又不得不如此。

这样分析下来，经济适用房根本不符合保障性住房的原则。可是为什么这样一个不靠谱的政策居然能够在全国大行其道？原因有二。 一是政府想讨好老百姓。政府自己又不创造财富，就是拿大家的钱帮助大家，乐得做顺水人情。百姓其实是受蒙骗的，以为得到了好处。这个好处是以其他更多的人受损为代价的。有时候经济适用房就是靠强制性向郊区农民低价征地造起来的。损害的是郊区农民的利益。许多拆迁冲突，上访闹事，就是因为建经适房而发生的。这时候受损的人明显可见。用损害农民的方法让城里人买便宜房显然是不合理的。也有些情况是用公有土地建经适房。表面上看没有人受损，实际上是全国人民受损，也毫无合理性可言。 二是政府官员自己有好处。分配经适房的权力在政府手里。分配经适房的官员可近水楼台先得月。事实上经适房很大一部分就分给了有权有势的政府官员。一般平民百姓能分到手的很少。是政府官员的私利驱动了经适房政策的通过和实施。要想取消它还真不容易。

更糟糕的是经适房创造了贪污腐败的机会。如果不是经济适用房的政策，这种腐败本来根本不会出现。为了一个完全不必要的政策，又创造出许多贪污腐败的机会，进一步败坏了社会风气。各地因经适房分配不公出的问题已经不计其数

这样看来，保障性住房应该就是廉租房或公租房等不涉及产权的政府建房，以低于市场价格的租金出租给贫困户。这类廉租房的建筑标准是比较低的，可能没有私人厕所，只有公用厕所（例如香港地区的做法）。这样能降低造价，为更多的贫困户提供帮助。

政府是不创造财富的，政府的资源就是全国人民的资源。拿全国人民的资源帮助穷人，大家不会有太大的意见。但是为什么拿全国人民的资源帮助中产阶级买房，就没有太多的理由了。政府有责任解决每个人的住房问题，但是没有责任满足每个人对房产的占有欲望。这是性质完全不同的两件事。不论是谁，买房只能靠自己，靠政府是讲不通的。没有地方住，可以找政府想办法，但是不涉及所有权。

房价为什么高？关键是有人不怕贵。这和我国的宏观形势有关。我国的经济增长率很高，每年的财富生产能够增加10％左右。这么多的财富被生产出来，但是消费掉的并不多，有大约40％储蓄起来了。再加上财富分配的不均，收入高的人年增收入远超过10％。他们手中的钱很多，又找不到合适的投资机会，于是就拿他们的储蓄买房。要想房价下降，这几个条件必须有所改变。或者是经济增长率下降，消费扩大储蓄减少，财富分配均匀化，有更多的投资机会；或者是大大增加房屋的供给，关键是增加土地的供应。我国房屋供应的限制就在于用于开发的土地不足。特别是为了粮食安全考虑，而过度限制农田转用于开发用地。这项政策应该改变。

我国房地产市场偏向档次高的客户，普通的低档房盖得很少，正是与我国财富分配中贫富差距悬殊有关。房地产市场反映了收入分配的状况，不改变收入分配，房地产业的结构同样改变不了。

一个市场中有少量的投机是好的，此时投机能够创造财富。但是投机过多时，价格被投机者控制，投机变成赌博，就不能创造财富。不光房地产市场是这样，其他一切市场都是这样。 股票市场上的投机者，低价买进高价卖出，如果价格预估正确，他们在赚钱的同时也能为企业的优劣变化指出方向，所以对社会是有贡献的。他们所赚的钱就是社会给他们的回报。但是如果他们判断错误而赔钱，把走向恶化的企业看成好企业，把坏企业的股票价格抬上去，最后事实证明企业的股票价格下降，社会就会对他们惩罚。这是很公平的。 但如果投机者人数太多，会扰乱正常的市场秩序，使价格陷入混乱。投机者失去方向，投机就变成了赌博。投机能创造财富，而赌博是不能创造财富的。比如我国的股票市场，一年的换手次数达到7次，外国的换手率只有一两次，说明投机活动太多。不改变这样的状况，股票市场很难正常化，金融危机也更容易发生。房地产市场也是同样的道理，我们必须防止过度投机，它有害于国民经济。

回过头来总结，我们有三方面的问题：收入分配不均、土地和资金市场缺乏竞争、金融市场没有更多的投资渠道，是造成房地产业扭曲的根本原因。这些原因不改变，扭曲就不会得到纠正。

政府用强制手段从农民手里低价拿地，再用所造成的价差补贴城里人以低价买房。这就是经济适用房政策背后的游戏。它的实质是让农民补贴城里人，是一种倒行逆施的收入分配政策，是在我国已经扭曲了的收入分配现状中火上浇油。最近全国各地大量农民上访，官民冲突的一个主要原因就是和土地有关的纠纷。

解放前的农业是一个相当高效的行业，后来变成一个非常糟糕的行业。其区别何在？一言以蔽之，在于有没有参与者的自由。不论出于什么好心，如果违背了自由的原则，好心也会办坏事。反之，如果有了自由的选择，虽然是坏的政策，也不会实施。自由可以屏蔽掉坏事，不让它发生。因为当事者最知道自己的利益何在。这条原则是一切经济问题的基本道理，从政者万万不可违背这个原则。

不但在农业方面是这样，在其他方面也一样。切记：自愿原则，不容随便破坏。政策的好坏不在乎制定者的判断，而在乎能不能在自愿的基础上行得通。除了税收、环保、防止不良外部性等少数几种情况需要强制干涉，政府切忌自以为是，强迫实施大家不愿意做的事。什么是市场？其实就是顺乎自然。计划为什么不好，就因为它违背民意。是谁有权强迫别人做不愿意做的事？只有政府才能。所以政府千万要小心谨慎，不可违背自然，造成严重后果。

由于对土地没有明确的所有权，发生了公地悲剧，大家只管使用，不管维护，地力下降，有机质减少，而且生产积极性不能保护。为了解决这个问题，政策规定土地承包30年不变，甚至50年不变。可是所有权还是模糊的。更准确地讲，农民还是没有对土地的所有权。

为了解决和所有权相关的问题，政府可以说是费尽了心思。再三强调承包制不变，延长承包期，又说要加强土地的流转，又是土地入股，土地可以作抵押，土地可以置换出租，还有小产权制，花样多得眼花缭乱。但是最根本的所有权问题始终避而不谈。而恰恰所有权才是问题的根子。它是绕不过去的。

作为慈善事业的扶贫，只能有少量人士参与，它成不了正规的金融业。要使小额贷款成为农村金融的一个角色，必须能够商业化，能够吸引大批资金进入，所以商业化是必需的。

现在社会上出现了一种现象，我认为很不好。那就是一方面为穷人说话的人很多，替富人说话的人很少；另一方面为富人办事的人很多，为穷人做事的人很少。 出现这种现象的原因很简单。为穷人说话能够得到社会上大多数人的赞同。穷人是弱势群体，需要有人为他们说话。哪怕说错了，也不用担心。因为立场不错，顶多是技术性错误。说话的人考虑自己的社会影响和对自己的舆论评价，为穷人说话是不会出问题的。我国是一个特别讲究立场的国家。立场错了一切都错。谁敢犯立场性的错误去为富人说话呢。所以都站在保险的立场上为穷人说话。 为富人说话则不同。由于大众受马克思剩余价值学说的灌输，富人被认为是剥削者。为剥削者说话当然错了。所以话还没有说，立场先已经错了。谁会去做这种吃力不讨好的事呢！ 至于做事，为富人做事是有酬劳的，所以大多数人愿意为富人做事。而为穷人做事很难有酬劳，所以为穷人做事的人比较少。于是结果是许多人为富人做事，为穷人说话；很少人为富人说话，为穷人做事。这样一个社会是很不正常的，是容易出问题的。所以我要反其道而行之，为富人说话，为穷人做事。

有不少情况，企业家犯法是因为政府当局处置不当。例如税务局征税，有许多不合理的规定。企业家多次反映，当局起初不认错，后来各方面反映实在太强烈，不得不承认有毛病，但是至今不改。企业和政府完全不在一个平等的地位上，吃亏的永远是企业。企业家对这种种不合理的做法无法抗衡，只好以恶治恶，用做假账来对付。这样企业家显然是犯法了，但是确实是事出有因，起因还在政府一边。类似的情况不仅发生在企业家那里，也发生在一般人民群众那里。要说犯罪，就不仅仅是企业家的事了，所以光怪企业家是没有多少道理的。

社会表扬做慈善的人，这是一个正常社会所应有的习惯。过去有些人强调做好事要不留名，留了名就不是真正的好事。这种理论非常有害。为什么我们对待做好事的人如此苛刻呢？正因为做好事的人不够多，所以需要社会的表扬，鼓励大家多做好事。哪怕人们做好事是为了得到表扬，只要是真正的好事又有何妨？我们不否认有些企业做慈善有广告宣传的动机，但只要他们做的事真正帮助了有困难的人，得到表扬是很公平的。而且这对全社会有益，有什么理由反对呢？如果我们真正对贫苦人充满着同情心，我们一定会欢迎一切对穷人有益的活动。至于出钱做慈善出于什么动机，根本不是我们要关心的问题。穷人的生活能否得到改善才是我们关心的事。有些人自己不参加慈善活动，还要对别人的参与吹毛求疵，这种心理很不健康，对社会是不利的。

在中国做慈善并不能给富人带来财产的安全和社会的名望，而是恰恰相反。富人露富的结果是更不安全，名声更糟。这是中国富人不愿意出钱做慈善的根本原因。中国的环境很不同于美国。在美国财富象征着个人的成功，是大家学习的榜样。在中国则不同。中国的富人是挨骂的对象，是剥削的典型。不露富还好一点，露富是一点好结果都不会有的。

拥有财产会带来剥削者的坏名声，财产的安全缺乏保障。在这样的社会中露富是最愚蠢的做法。所以富人的对策是不声不响地把财产转移去外国安全的地方，而不是捐款做慈善。这就是近年来大批富人移民西方国家的背景。

这条道路就是李连杰所倡导的壹基金，每人每月捐一元钱。我认为这个方向符合中国的国情，能有广阔的发展前途。但是壹基金曾经遭遇很大困难。原因和国家对慈善事业的垄断企图有关。中国政府的基本态度是鼓励民间拿钱，但是操作要由政府来做。如果民间自己拿钱，自己操作，政府是不鼓励的。这一点很明显表现在慈善组织注册的规定条文，在善款纳税的区别对待上。特别是民间的慈善极难获得合法身份，因此他们不能在银行开设账号，没有自己的图章，也开不出捐款的合法收据。因此也不能向公众募捐，这些事只有挂靠政府的慈善机构才能做。当然，如果政府的慈善做得很好，也未尝不可。问题在政府的慈善事业往往毛病丛生。救济目标缺乏合理的针对性，操作不透明，没有热情，是冷冰冰的照章办事，还有不少贪污浪费。使得大家出钱不放心。这就大大阻碍了中国慈善事业的发展。

政府不同于一般民间组织，它最重要的特点是具有武力做后盾，可以用强制措施来达到某一特定的目标，如国防、公安、纳税、食品安全，甚至环保，但是不包括慈善。做慈善不需要任何强制性的力量，相反，要的是热情和细致。这正好是政府所缺乏的。所以世界各国的政府都不做慈善（但是政府调整收入差距，提供社会保障），慈善是留给民间做的事业。

经济学中的享受是指对物质消费的满足感，而不是从攀比得到的满足感。买几千几万元的手表或手袋，得到的是从炫耀来的攀比满足感。严格讲，攀比的满足是为了别人，不是为了自己。如果没有别人在场，就不会有攀比的满足感。为了别人的羡慕而消费是愚蠢的消费。为了别人的福利而消费是聪明的消费。比如买路边小摊的商品，不但满足了自己的需求，又帮助摆摊的人提高了收入，利人利己，是聪明的消费。这种消费有利于缩小贫富差距。

从这个角度看，贪污分子最倒霉。他们贪污得来的钱很多，但是不敢露富，到处装穷，一点也没享受着，天天还要担心受怕。物质享受没得到，倒是精神负担非常重。两头都没捞着，非常不合算。如果他们想通了，就不会贪污了。

值得注意的是我们千万不要做相反的事，拿穷人的钱去补贴富人。当然，很明显这种政策是不会发生的，但是隐蔽地补贴富人是可能有的。这值得大家密切注意。比如说，为了照顾穷人保持低电价，实际上富人得到的好处远远大于穷人得到的好处。因为富人用电量远超过穷人用电量。结果是拿广大电力用户的钱去更多地补贴了用电量大的富人。这种为了穷人而被富人搭便车的例子比比皆是。本来是想缩小一点贫富差距，结果适得其反。而且这种政策很难纠正，因为表面上这是为了穷人，叫起来振振有词，反对它要冒很大的风险。

